### ISSUE TITLE
Custom checks gives wrong guide link

### ISSUE THREAD

**Issue by michal-adamkiewicz** [bridgecrewio/checkov#1433]
**Describe the bug**
Custom checks gives wrong URL in **guide** section. There is always URL pointing about NACLs and subnets :)
https://docs.bridgecrew.io/docs/ensure-that-all-nacl-are-attached-to-subnets

**To Reproduce**
Launch any custom-check using plan stored in JSON

**Expected behavior**
Guide section should or omitted or there should be a way to inject custom URL for further instructions 

**Screenshots**
Check: CKV2_AWS_1: "Check that all resources are tagged with the keys - environment and team_name"
	FAILED for resource: aws_instance.this
	File: /tf.json:0-0
	Guide: https://docs.bridgecrew.io/docs/ensure-that-all-nacl-are-attached-to-subnets

**Desktop (please complete the following information):**
 - Checkov Version 2.0.305 

P.S Thank you very much guys for closing (and solving) my previous issue about not triggering custom checks based on json terraform plan at all 👌 💪 🙇

**Comment by VAnagani** [comment]
Ability to inject custom URL to custom checks would be great. Looking forward for this feature.

**Comment by nickgibbon-nationwide** [comment]
Hello @michal-adamkiewicz - Could you please show you're custom check implementation?

It's outputting this URI because CKV2_AWS_1 is an ID which maps to this guide here: https://www.bridgecrew.cloud/api/v1/guidelines

The question is whether you are including a check ID in your custom check configuration? In which case your can probably just change it. Or, it is setting this CKV2_AWS_1 as a default somewhere.

I'm going to continue looking but if you could input this it would be useful.

**Comment by njgibbon** [comment]
Hello @michal-adamkiewicz - Could you please show you're custom check implementation?

It's outputting this URI because CKV2_AWS_1 is an ID which maps to this guide here: https://www.bridgecrew.cloud/api/v1/guidelines

The question is whether you are including a check ID in your custom check configuration? In which case your can probably just change it. Or, it is setting this CKV2_AWS_1 as a default somewhere.

I'm going to continue looking but if you could input this it would be useful.

**Comment by njgibbon** [comment]
I am fairly sure if you mark you're custom check id fields with an ID `CKV2_CUSTOM_1` for example that this will work for you. I believe you have copied `CKV2_AWS_1` from the guide, but there it is meant as an example to be replaced. Still, this could be made a bit clearer for custom checks.
