### ISSUE TITLE
GitHub CodeQL Upload SARIF Results Failure

### ISSUE THREAD

**Issue by ejohn20** [bridgecrewio/checkov#1521]
Uploading the SARIF formatted output to the GH repo fails. It does not appear to be valid SARIF according to the parser. Using the `github/codeql-action/upload-sarif@v1` produces an error message with invalid data.

**To Reproduce**
1. Create a GH Action with the following steps to run the checkov scan and generate a `checkov.sarif` results file:

```
- name: Set up Python 3.7
   uses: actions/setup-python@v2
   with:
     python-version: 3.7.7
 - name: Run checkov analysis
    run: |
      python --version
      python -m pip install --upgrade pip setuptools
      python -m pip install --upgrade 'checkov==2.0.360'
      checkov --version
      checkov --framework terraform -s -d src/ -o sarif > checkov.sarif
```

2. Add another action to upload the SARIF results to the repo:

```
- name: Upload SARIF file
  uses: github/codeql-action/upload-sarif@v1
  with:
    sarif_file: checkov.sarif
```

3. See error message:

```
Error: Unable to upload "checkov.sarif" as it is not valid SARIF:
- instance.runs[0].tool.driver.rules contains duplicate item
Error: Unable to upload "checkov.sarif" as it is not valid SARIF:
- instance.runs[0].tool.driver.rules contains duplicate item
    at validateSarifFileSchema (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:196:15)
    at uploadFiles (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:256:9)
    at Object.uploadFromActions (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:132:18)
    at async run (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:49:29)
    at async runWrapper (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:61:9)
```

**Expected behavior**
SARIF results are uploaded to GH and display on the Security tab.

**Comment by ejohn20** [comment]
Further analysis of the JSON file shows that the rule ids appear to be duplicated based on how many "results" are in the findings. For example, I'm seeing two `CKV_AWS_121` ids in the `rules` array. Also 17 `CKV_AWS_111` rule ids in the array. 

I believe the `rules` array is intended to be a distinct list of all rules supported by the scanner. The `results` array is intended to hold the  1 ---> many list of instances. Each result references the corresponding `ruleId` found in the distinct list of `rules`.

**Comment by nimrodkor** [comment]
@ejohn20  you're absolutely right!

We'd love a contribution, should be around here somewhere:
https://github.com/bridgecrewio/checkov/blob/d181aa0c29d2b5220e24c8f24f3f426870ff9dd3/checkov/common/output/report.py#L192

**Comment by harringj** [comment]
As it turns out, my fix for this issue contains a bug: 
![image](https://user-images.githubusercontent.com/21954788/132401167-31f085d3-7fa5-45e1-b803-a6ab7a1bbebd.png)
As the screenshot indicates, the cause is https://github.com/bridgecrewio/checkov/blob/507340f8bc7e9d9b58263c9a66bbdd05752dae3a/checkov/common/output/report.py#L212 The call to rules.index(rule) is searching for the current rule object in the rules array, but no such object will exist whenever the values of record.check_id are the same. There will, however, be another rule object in the array with the same id.

I'm opening a PR, which I'll link to this issue, which resolves the error by comparing the value of rule['id'] with each rule in the array until it finds the index of the rule with the matching id. Apologies for letting this slip past me in the first place!
