### ISSUE TITLE
VS Code Extension not working

### ISSUE THREAD

**Issue by JaimePolo** [bridgecrewio/checkov#1583]
**Describe the bug**
when running Checkov scan on the command palette on VS Code nothing happens and the Checkov extension has an "X" next to it.

**Expected behavior**
Scan TF files.

**Screenshots**
![image](https://user-images.githubusercontent.com/13440682/132369026-495295d6-1718-4757-8f42-ca46758fce3e.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur, version 11.5.2
 - Checkov Version: 2.0.390

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by schosterbarak** [comment]
hey @JaimePolo can you check again on latest version?

**Comment by JaimePolo** [comment]
I updated to version 2.0.420 and still the same. I am running on a M1 Mac architecture.

**Comment by jasonckeating** [comment]
Same here on version 2.0.461.
Macbook Pro 2017.

I believe this is a vsCode extension issue, since 1.0.48 displays the 'x' no matter what.

@JaimePolo, If you revert the vsCode extension to 1.0.47, which still uses checkov v2.0.461, it scans properly.

Created a [checkov-vscode issue](https://github.com/bridgecrewio/checkov-vscode/issues/70) for this.

**Comment by nimrodkor** [comment]
Hi @richardj-bsquare , I'll get those issues looked at soon.
Closing it for now as it is relevant only for the plugin. For further issues regarding the plugin - https://github.com/bridgecrewio/checkov-vscode/issues
