### ISSUE TITLE
Possibility of Parsing a variable while creating custom policies

### ISSUE THREAD

**Issue by abhi06991** [bridgecrewio/checkov#1750]
Hi Team,

I am not sure whether this is already possible, but I have trued everything but not able to make this work.

so, there is this `TF `file, which contains an IAM policy defined as JSON in a `variables` file. Assuming the policy is vulnerable and some important attributes missing, checkov doesn't identify that, since it didn't parse the variable. 

We are writing some custom Checkov rules, is there a way to parse the variable and get the JSON data?

Thanks!

**Comment by nimrodkor** [comment]
Hey @abhi06991 , can you share some anonymized templates for our testing?

**Comment by andresjz** [comment]
I have a similar issue where the policy is not parsed, this is an example of an `s3_bucket_policy`, if a try to evaluate something from the policy I cannot do that because in the value I got `data.aws_iam_policy_document.this.rendered`

the data can be a json file as @abhi06991 mentioned, in my case I put in that way because I already have it


```
data "aws_iam_policy_document" "this" {
  statement {
    effect  = "Deny"
    actions = ["s3:GetObject"]
    resources = [
      "${aws_s3_bucket.code_artifacts.arn}/*"
    ]
    principals {
      type        = "AWS"
      identifiers = ["*"]
    }
    condition {
      test     = "StringNotLike"
      variable = "aws:userId"
      values = [
        "${aws_iam_role.code_artifacts.unique_id}:*"
      ]
    }
  }
}

resource "aws_s3_bucket_policy" "deploy_user_policy_1" {
  bucket = aws_s3_bucket.this.id
  policy = data.aws_iam_policy_document.this.rendered
}
```
