### ISSUE TITLE
Parsing error with Helm values file

### ISSUE THREAD

**Issue by brettcurtis** [bridgecrewio/checkov#1927]
**Describe the bug**
When running checkov against a few helm installed applications we use (GoCD & Hazelcast) we get a parsing error back.

**To Reproduce**

**GoCD**

1. `helm repo add gocd https://gocd.github.io/helm-chart`
2. `helm inspect values gocd/gocd > gocd.yaml`
3. `checkov -f gocd.yaml`

**Hazelcast**

1. `helm repo add hazelcast https://hazelcast-charts.s3.amazonaws.com`
2. `helm inspect values hazelcast/hazelcast-enterprise > hazelcast.yaml`
3. `checkov -f hazelcast.yaml`

**Expected behavior**
I'd expect the following to not report back the parsing error:

**GoCD**

```none
By bridgecrew.io | version: 2.0.555 
Update available 2.0.555 -> 2.0.566
Run pip3 install -U checkov to update 


cloudformation scan results:

Passed checks: 0, Failed checks: 0, Skipped checks: 0, Parsing errors: 1

Error parsing file gocd.yaml
secrets scan results:

Passed checks: 0, Failed checks: 2, Skipped checks: 0

Check: CKV_SECRET_6: "Base64 High Entropy String"
        FAILED for resource: 73726940fbbe4f60d623a48c0cf51ba15ececae6
        File: /gocd.yaml:238-239
        Guide: https://docs.bridgecrew.io/docs/git_secrets_6

                238 |       secretName: gocd-server-ssh


Check: CKV_SECRET_6: "Base64 High Entropy String"
        FAILED for resource: 363213b0ce319aa2eaa9bf606f726c2617bcc259
        File: /gocd.yaml:398-399
        Guide: https://docs.bridgecrew.io/docs/git_secrets_6

                398 |       secretName: gocd-agent-ssh
```

**Hazelcast**

```none
❯ 
By bridgecrew.io | version: 2.0.555
Update available 2.0.555 -> 2.0.566
Run pip3 install -U checkov to update


cloudformation scan results:

Passed checks: 0, Failed checks: 0, Skipped checks: 0, Parsing errors: 1

Error parsing file hazelcast.yaml
```

**Additional context**
The failed checks I'm getting back are also a false positive, I can do a new issue there if ya want.

**Comment by metahertz** [comment]
Taking a look at this @brettcurtis 
Thanks for the detailed issue report!

**Comment by metahertz** [comment]
Interesting!

So the helm support in Checkov is designed to find helm charts themselves (directories containing `Chart.yaml`'s) then auto-template them out to K8S manifests and then run them through the kubernetes policies, with some logic to ensure we know which resource from the chart mapped to the templated resource etc.

As this is not a Chart, but a values file, Checkov doesn't know what to do with it, so it's landing on the CloudFormation scanner to try and scan the file (hence the false positives).

If you force checkov to just use the k8s/helm frameworks, you'll get no results due to the above:

```
(1927) ➜  1927 checkov -f gocd.yaml --framework kubernetes

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.572

(1927) ➜  1927 checkov -f gocd.yaml --framework helm

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.572
```

A workaround would be to template out your specific `values.yaml` (in your case, `gocd.yaml` into the resulting k8s template, and pass it directly to the Kubernetes framework (which is effectively what Checkov does when it finds a helm chart anyway!)

```
(1927) ➜  1927 helm template gocd/gocd -f gocd.yaml > k8s-template.yaml
(1927) ➜  1927 checkov -f k8s-template.yaml --skip-check CKV_K8S_21
```

The only other thing to note is that i've skipped check `CKV_K8S_21` which alerts on default namespaces, since HELM manages our namespaces, we always skip this internally when using the HELM framework.

I'm gonna tag the issue as feature and bug, as i think you've highlighted a very valid usecase for helm-chart consumers, rather than helm chart creators/contributors, which was the original design for the helm functionality! :) 

Does the workaround help at all? Thinking of updates to checkov to enable this functionality I can't initially see anything in the `gocd.yaml` which would allow us to autodetect it as a helm values file, or a way to tie it back to the repo/chart (as all of that information is on the `helm inspect values` command. 

It may be we'd need a `checkov --helm-inspect-values gocd/gocd` or something similar in order to have the context of the chart, template it out ourselves etc.

**Comment by brettcurtis** [comment]
Thanks Matt, makes sense now. I'm glad my lack of understanding could lead to a potential use case :D The W/A is good, maybe in the future we could put some comment in the file that checkov looked for so it would know it was a values file and the k8s templating could all happen in the background like ya mention.
