### ISSUE TITLE
"Got a substring with double underscore, which is not allowed" => Avoid that warning when parsing AWS Tags?

### ISSUE THREAD

**Issue by JPLachance** [bridgecrewio/checkov#2082]
**Describe the bug**
Checkov is printing a ton of warnings in our projects since the addition of this line: https://github.com/bridgecrewio/checkov/blob/e78202ddc44c8aea72e9fd7a0d13e81296d4e533/checkov/terraform/graph_builder/variable_rendering/safe_eval_functions.py#L188

Basically, we use double underscore in our AWS tags, so each time we run Checkov, we have these warnings. They are polluting the rest of Checkov useful intel. 

**To Reproduce**
1. Create any Terraform ressource with `__` in an AWS tag
2. Scan that resource

**Expected behavior**
I would expect Checkov not to print me that warning for our AWS tags

**Desktop (please complete the following information):**
 - OS: Linux
 - Checkov Version: 2.0.421

**Comment by JPLachance** [comment]
@rotemavni, you most likely know why this warning exists. I'm sure there is a good reason for it. Can you help me understand?

**Comment by rotemavni** [comment]
Hi @JPLachance, thank you for bringing this issue to our attention.
Handling this issue was introduced in this PR https://github.com/bridgecrewio/checkov/pull/1195, originally it was an error, but we reduced the severity to a warning.

We wanted to eliminate cases where evaluating string values could cause harm, such as segmentation faults - as you can see in the following test case: https://github.com/bridgecrewio/checkov/blob/8e0989c6270f5ebf080fa77c08334c6a81aa256e/tests/terraform/graph/variable_rendering/test_string_evaluation.py#L327-L343

This warning allows gaining visibility on bad values used in terraform code, however I understand it caused too much data to be printed. 
How do you feel about reducing this log into a `debug`?

**Comment by JPLachance** [comment]
Hello,

Reducing it to a debug would fix the issue yes. At the moment, I use [Checkov as a Terragrunt hook](https://source.coveo.com/2021/03/02/checkov-terragrunt-hook/). By lowering the logging statement to a debug log, those warning will stop being printed in each `terragrunt plan` I do. Our eyes will be happy!

Thank you for your quick answer 😄

Are you opening the PR?
