### ISSUE TITLE
CKV_AWS_116: DLQ applies only to async invocations

### ISSUE THREAD

**Issue by asyschikov** [bridgecrewio/checkov#2194]
**Describe the issue**
CKV_AWS_116: "Ensure that AWS Lambda function is configured for a Dead Letter Queue(DLQ)"
DLQ applies only to synchronous Lambda invocations, so if you have a REST API for example it won't have any effect and thus is unnecessary. The rule fires up for all Lambdas.

I understand that unfortunately in a general case it is impossible to figure out from a CloudFormation template with a Lambda function whether it is synchronous or asynchronous, because you can call any function in either way with AWS CLI or API, without any event mapping.

**Comment by gruebel** [comment]
hi, actually the DLQ is for asynchronous Lambda invokes not synchronous. We already have an open issue talking about extending the check to allow different configuration via event invoke config #1795
Since we don't know, how a user will use the Lambda, we give recommendation what should be configured, but if it doesn't apply to some of the Lambdas, then feel free to add a skip comment and details about not being useful for that case.

**Comment by asyschikov** [comment]
@gruebel sorry, you are right, I had a brain zap, it is other way around indeed. I would add a comment but I pipe autogenerated CFN from CDK so no easy way to add comments. Any chance checkov could support metadata section of CFN for suppression? This way you can link a suppress statement with a resource without hand-writing CFN.

**Comment by gruebel** [comment]
not yet, but an issue exists 😉 just add your 👍 here #1931 I also thought this would be helpful for CDK setups
