### ISSUE TITLE
Failing to pull latest docker image (2.0.743)

### ISSUE THREAD

**Issue by zchandrahasan** [bridgecrewio/checkov#2248]
**Describe the bug**
We are unable to pull latest docker image for latest version of checkov.

**To Reproduce**
Run /usr/bin/docker pull bridgecrew/checkov:2.0.743

**Expected behavior**
image should be pulled correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/33101843/150567351-4ce9f49a-636a-461b-b27a-c0e7011cca18.png)

**Desktop (please complete the following information):**

OS: ubuntu 20.04.2 LTS
Checkov Version 2.0.743

**Additional context**
error:
`/usr/bin/docker pull bridgecrew/checkov:2.0.743
  Error response from daemon: manifest for bridgecrew/checkov:2.0.743 not found: manifest unknown: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 7.488 seconds before retry.`

**Comment by HariSekhon** [comment]
Same here, the github action `uses: bridgecrewio/checkov-action@master` is broken due to this missing docker image tag.

Perhaps this is a race condition between master branch update and the publishing of a new docker image tag?

There was bridgecrew/checkov:2.0.742 was pushed an hour ago, so alternatively perhaps master was updated to the wrong version?

**Comment by gruebel** [comment]
sorry, it was indeed a race condition between two builds. Merged an other PR to enforce a new build and there is now a `2.0.744` image tag and the `latest` tag should reference it.
