### ISSUE TITLE
CKV_AWS_109 should pass for KMS key policies

### ISSUE THREAD

**Issue by MrHash** [bridgecrewio/checkov#2336]
According to the docs at https://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html KMS key policies can use resource `*` to represent the current key.

<img width="756" alt="Screen Shot 2022-02-04 at 11 09 56" src="https://user-images.githubusercontent.com/390925/152519681-9591f677-429d-4165-a346-fa9c2b45b28a.png">

**Comment by gruebel** [comment]
Hi @MrHash thanks for creating the issue.

This is true for any resource policy, not limited to KMS key policies. Since we don't know, what you will use a `data.aws_iam_policy_document` for, we assume the worst.

If this check doesn't fit for the policy document you defined, just add a skip comment with you reasoning and we don't flag it anymore. Alternative you could also use inline policies with `jsonencode` then this check won't be triggered at all.
