### ISSUE TITLE
Bicep false CKV_AZURE_23

### ISSUE THREAD

**Issue by acorbos** [bridgecrewio/checkov#2632]
Hi,
I get CKV_AZURE_23 on this simple bicep file:

`
@description('SQL Logical server.')
param sqlLogicalServer object

@description('The SQL Logical Server password.')
@secure()
param password string

param tags object

var defaultAuditActionsAndGroups = [
  'SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP'
  'FAILED_DATABASE_AUTHENTICATION_GROUP'
  'BATCH_COMPLETED_GROUP'
]

resource sqlLogicalServerRes 'Microsoft.Sql/servers@2021-02-01-preview' = {
  name: sqlLogicalServer.name
  location: resourceGroup().location
  tags: tags
  identity: {
    type: sqlLogicalServer.systemManagedIdentity ? 'SystemAssigned' : 'None'
  }
  properties: {
    administratorLogin: sqlLogicalServer.userName
    administratorLoginPassword: password
    version: '12.0'
    minimalTlsVersion: sqlLogicalServer.minimalTlsVersion
    publicNetworkAccess: sqlLogicalServer.publicNetworkAccess
  }
}

// Audit settings need for enabling auditing to Log Analytics workspace
resource auditSettings 'Microsoft.Sql/servers/auditingSettings@2021-02-01-preview' = {
  name: 'default'
  parent: sqlLogicalServerRes
  properties: {
    state: 'Enabled'
    auditActionsAndGroups: defaultAuditActionsAndGroups
    storageEndpoint: ''
    storageAccountAccessKey: ''
    storageAccountSubscriptionId: '00000000-0000-0000-0000-000000000000'
    retentionDays: 0
    isAzureMonitorTargetEnabled: sqlLogicalServer.diagnosticLogsAndMetrics.auditLogs
    isDevopsAuditEnabled: sqlLogicalServer.diagnosticLogsAndMetrics.microsoftSupportOperationsAuditLogs
  }
}
`

My command is:
`checkov -f .\sql-logical-server.bicep --framework bicep`

Expected: no CKV_AZURE_23, since there is state: 'Enabled' in auditingSettings.properties
Version: 2.0.962

**Comment by gruebel** [comment]
hi @acorbos thanks for creating this issue and I'm happy that you gave the Bicep runner a try. It is still in an early stage and I'm improving it step by step.

**Comment by acorbos** [comment]
@gruebel thanks for looking into it, I couldn't find the code. Is it somehow converting to ARM and then using the ARM checks?
I'm asking because I wanted to switch to ARM and I have the same problem with it.
See https://github.com/bridgecrewio/checkov/blob/master/checkov/arm/checks/resource/SQLServerAuditingEnabled.py
I think it should check on server level, not on database level if the message is "Ensure that 'Auditing' is set to 'Enabled' **for SQL servers**". By the way, that blank there, shouldn't it be a slash between MicrosoftSql and servers?
"Microsoft.Sql servers/databases/auditingSettings"

**Comment by gruebel** [comment]
@acorbos you are right, but it is even a bit more complicated, but I'm working on a fix. It won't cover all possibilities, but it should be better than now 🙂

**Comment by aspp644** [comment]
Hello!

I am also getting the same error and was using Bicep as well to create SQL PaaS.

I added this resource block in my bicep template for creation of SQL PaaS.

resource auditSettings 'Microsoft.Sql/servers/auditingSettings@2021-08-01-preview' = {
  name: 'default'
  parent: serverName_resource
  properties: {
   ...
    **state: 'Enabled'**
   ...
  }
}

I also added resource blocks for the following with     **state: 'Enabled'** in properties.
resource auditSettingsdatabase 'Microsoft.Sql/servers/databases/auditingSettings@2021-08-01-preview'

resource extendedAuditingSettings 'Microsoft.Sql/servers/databases/extendedAuditingSettings@2021-08-01-preview'
resource databaseExtendedAuditingSettings 'Microsoft.Sql/servers/databases/extendedAuditingSettings@2021-08-01-preview'

Still getting this checkov scan failed. "Ensure that 'Auditing' is set to 'Enabled' for SQL servers"
https://docs.bridgecrew.io/docs/bc_azr_logging_2

**Comment by gruebel** [comment]
@aspp644 did you try it with the latest `checkov` version? which one are you using right now?

**Comment by aspp644** [comment]
Hello @gruebel  - I'm using Checkov - v2.0.983

**Comment by GABRIELNGBTUC** [comment]
The issue seems to be back as I have the following module triggering the failed test
```bicep
resource la_resource 'Microsoft.OperationalInsights/workspaces@2022-10-01' existing = {
  name: la_name
  scope: resourceGroup()
}

resource diagnosticSettings 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  scope: sqlServer::db_resource
  name: 'sqllogs'
  properties: {
    workspaceId: la_resource.id 
    logs: [
      {
        category: 'SQLSecurityAuditEvents'
        enabled: true
      }
    ]
  }
}

resource sqlServer 'Microsoft.Sql/servers@2021-11-01' existing = {
  name: sql_server_name
  resource audit_resource 'auditingSettings' = {
    #disable-next-line decompiler-cleanup
    name: 'default'
    properties: {
      state: 'Enabled'
      isAzureMonitorTargetEnabled: true
    }
  }
  resource db_resource 'databases' existing = {
    #disable-next-line decompiler-cleanup
    name: sqldb_name

    resource audit_resource 'auditingSettings' = {
      #disable-next-line decompiler-cleanup
      name: 'default'
      properties: {
        state: 'Enabled'
        isAzureMonitorTargetEnabled: true
      }
    }
  }
}
```

If I add an extendedAuditingSettings inside the database resource definition, an additional failed test appears. If  I add any of the auditing settings inside the server resource definition, a failed test appears for each as well.

**Comment by GitRitz** [comment]
Adding signal from a recent investigation. We hit this exact issue on Bicep-compiled ARM JSON for `Microsoft.Sql/servers/auditingSettings` and `Microsoft.Sql/servers/securityAlertPolicies` child resources. CKV_AZURE_23, CKV_AZURE_24, CKV_AZURE_25, AZR-000186, AZR-000187 all fire even though the child resources are correctly defined.

## Reproduction (Bicep 0.40.x)

We tested 5 Bicep authoring patterns by running `az bicep build --stdout` and inspecting the generated `name` field:

| Bicep pattern | Compiled JSON `name` | Checkov-parseable |
|---|---|---|
| `parent: sqlServer` + `name: 'default'` (idiomatic) | `format('{0}/{1}', parameters('name'), 'default')` | ❌ |
| nested resource (`resource ... { resource ... }`) | `format('{0}/{1}', parameters('name'), 'default')` | ❌ |
| `'${sqlServer.name}/default'` (interpolation, symbolic ref) | `format('{0}/default', parameters('name'))` | ❌ |
| `'${name}/default'` (interpolation, param) | `format('{0}/default', parameters('name'))` | ❌ |
| `concat(name, '/default')` | `[concat(parameters('name'), '/default')]` | ✅ |

Only the explicit `concat()` form produces checkov-parseable output.

## The catch: Bicep linter conflict

Bicep's `prefer-interpolation` linter rule fires on `concat()` calls and recommends interpolation. Bicep's documented best practices push you AWAY from the only pattern that satisfies checkov. The two quality bars are in direct conflict.

Our workaround: use `concat()` with `#disable-next-line prefer-interpolation` directive and a comment pointing back to this issue.

```bicep
// checkov can't parse format() expressions emitted by Bicep's parent: syntax
// (https://github.com/bridgecrewio/checkov/issues/2632). Use concat() so the
// compiled ARM JSON name is a literal-shaped expression checkov recognizes.
#disable-next-line prefer-interpolation
resource auditingSettings 'Microsoft.Sql/servers/auditingSettings@2023-08-01-preview' = {
  name: concat(name, '/default')
  properties: { state: 'Enabled', retentionDays: 90 }
  dependsOn: [sqlServer]
}
```

## Suggested fix on checkov side

Two paths that would resolve the underlying issue:

1. **Evaluate ARM intrinsic functions** in the static parser. `format(format-string, args...)` with all-literal arguments is deterministic and could be evaluated to a string at parse time. Same for `concat()`, `resourceId()`, `subscriptionResourceId()`.

2. **Make these rules graph-aware.** The check at `checkov/arm/checks/resource/SQLServerAuditingEnabled.py` already has a comment acknowledging the limitation: "should be a graph check, due to the possible connection between Microsoft.Sql/servers and its child auditing settings resources." Following the `dependsOn` references from child to parent would resolve this without needing to evaluate intrinsic functions.

Either fix would also resolve CKV_AZURE_24 and CKV_AZURE_25 since they share the parent-child resolution logic.

Happy to test a candidate PR against our repo if helpful.
