### ISSUE TITLE
CKV_AWS_219 error when codepipeline artifact store bucket is encrypted

### ISSUE THREAD

**Issue by MrHash** [bridgecrewio/checkov#2852]
**Describe the issue**
CKV_AWS_219: "Ensure Code Pipeline Artifact store is using a KMS CMK" is seen when bucket is specifically server side encrypted with CMK using Terraform AWS provider v4

**Examples**
```
resource "aws_s3_bucket" "code_pipeline" {
  bucket        = "codepipeline-test"
}

resource "aws_s3_bucket_server_side_encryption_configuration" "code_pipeline" {
  bucket = aws_s3_bucket.code_pipeline.bucket
  rule {
    bucket_key_enabled = true
    apply_server_side_encryption_by_default {
      kms_master_key_id = data.aws_kms_key.artifacts.arn
      sse_algorithm     = "aws:kms"
    }
  }
}

resource "aws_codepipeline" "test" {
  name     = "test"
  artifact_store {
    location = aws_s3_bucket.code_pipeline.bucket
    type     = "S3"
  }
}
```

**Version (please complete the following information):**
 - Checkov 2.0.1074

**Additional context**
Using Terraform AWS Provider v4.9

**Comment by MooreDerek** [comment]
Not a AWS V4 Provider issue. The code is looking for `artifact_store-> encryption_key -> id` which is valid for both V3 and V4.

**Comment by MrHash** [comment]
Ok thanks for feedback, so since the bucket is already server side encrypted for all objects, should this check take that into consideration?

**Comment by nimrodkor** [comment]
It will complicate this check considerably, but I agree with this logic. I can suggest either:
1. Improving the check logic
2. Skipping this check on this resource with a comment that explains the CMK is from S3 SSE.

does that sound good @MrHash ?

**Comment by MrHash** [comment]
Of course i can skip this check in the meantime, fine by me

**Comment by gruebel** [comment]
This is actually a bit tricky, in a sense of what is actually happening in AWS.

A bucket default encryption only encrypts objects, when the uploader doesn't say otherwise. A real enforcement can only be achieved via a bucket policy. So, it is actually right to say you have to do both, add default encryption and then enable encryption for CodePipeline artifacts. But since both services are made by AWS, CodePipeline will not enforce an unencrypted upload to the bucket. So I actually wouldn't adjust the check to have a look on the config of the bucket and just keep the encryption enforcement of the artifacts.
