### ISSUE TITLE
Error parsing terraform file with multiline comment

### ISSUE THREAD

**Issue by julian7** [bridgecrewio/checkov#2933]
**Describe the issue**
Multi-line comments in terraform are not honored in some cases.

**Example Value**

```shell
❯ seq 1 4 | xargs -I, sh -c 'echo Example ,; cat ,.tf; checkov --quiet -f ,.tf'
Example 1
resource "null_resource" "nothing" {
    triggers = [
        /* "a",
        "b" */
    ]
}
terraform scan results:

Passed checks: 0, Failed checks: 0, Skipped checks: 0, Parsing errors: 1


Example 2
resource "null_resource" "nothing" {
    triggers = [
        /* "a", "b" */ ]
}

Example 3
resource "null_resource" "nothing" {
    triggers = [
        /* "a", "b" */
    ]
}
terraform scan results:

Passed checks: 0, Failed checks: 0, Skipped checks: 0, Parsing errors: 1


Example 4
resource "null_resource" "nothing" {
    triggers = [ /* "a", "b" */
    ]
}

❯ checkov -v
2.0.1110
```

**Comment by MooreDerek** [comment]
@julian7 The issue is with the parser used to parse the Terraform -> `python-hcl2`. The `lark` file definition does not provide for the `/*` syntax -> https://github.com/amplify-education/python-hcl2/blob/master/hcl2/hcl2.lark#L6 , instead it specifically marks them to be ignored -> https://github.com/amplify-education/python-hcl2/blob/master/hcl2/hcl2.lark#L74
Might work raising an issue on that project?

**Comment by erezsh** [comment]
If the problem lies in collecting the comments, maybe this will help: https://lark-parser.readthedocs.io/en/latest/recipes.html#collect-all-comments-with-lexer-callbacks
