### ISSUE TITLE
Implementing checkov with jenkins, have the problem with output

### ISSUE THREAD

**Issue by eternityduck** [bridgecrewio/checkov#2989]
I am running checkov in jenkins with sh, with this command
`docker run --rm --tty --volume $(pwd):/tf --workdir /tf bridgecrew/checkov --directory /tf`

I have only one error in one file, but all of my jobs failed.
![image](https://user-images.githubusercontent.com/70644164/169479296-a687edbc-913e-4db5-a605-c10e4400be68.png)
![image](https://user-images.githubusercontent.com/70644164/169479327-68d97c77-f928-4495-b3b0-1f507823947d.png)

Also checkov runs too long. What may be the problem of such a behavior?

**Comment by gruebel** [comment]
hi @eternityduck regarding the speed, it really depends on how many files you have in the repo you mount. If you only use Terraform, then you can limit the checking just to it by adding the flag `--framework terraform`, this should speed things up.

Why it fails all your jobs, I can't say, because it depends on how to integrated it into your Jenkinsfile.

**Comment by eternityduck** [comment]
I have only terraform files in my repo, like 250 files, I am integrating it in function with catchError function, where I run docker command and after call that function in pipeline call, don`t know how to describe better
