### ISSUE TITLE
Checks IDs changing

### ISSUE THREAD

**Issue by meghaddn** [bridgecrewio/checkov#3001]
Hi Team,

would like to request the check IDs do not get changed since we allowlist some checks which we run in our environment.
Eg : https://docs.bridgecrew.io/docs/bc_aws_iam_45 Check ID says CKV_AWS_61

whereas code is different for CKV_AWS_61.
Thanks!

**Comment by gruebel** [comment]
hey @meghaddn I reviewed the code and we didn't adjust the checks name and ID since October 2020.
We adjusted the logic inside to fix edge cases and bugs, but it is still checking for the same thing. Maybe it is confusing because the title in the linked docs is different than the name of the check.
Can you tell me what exactly fails now and passed before?
