### ISSUE TITLE
Support .tf.json

### ISSUE THREAD

**Issue by freddd** [bridgecrewio/checkov#315]
**Is your feature request related to a problem? Please describe.**
We would love to start using checkov but we are not using `.tf` files but rather `.tf.json` as outlined here: https://www.terraform.io/docs/configuration/syntax-json.html

**Describe the solution you'd like**
We should be able to use the tool no matter if the format is `.tf` or `.tf.json` as terraform supports both.

**Describe alternatives you've considered**

**Additional context**
After speaking to @schosterbarak on Slack it was concluded that I will create an issue here and in `python-hcl2` as that is the library used internally in the tool.

**Comment by robeden** [comment]
I wouldn't think python-hcl2 is going to support json since it's an HCL parsing library. I believe, however, that you should just be able to load .tf.json and .tfvars.json files using the standard json.load function and come up with the same result. I've casually tested that on my own stuff and it worked okay... though I admit I haven't tested thoroughly.

Here's a snippet of code I've used with an internal tool previously (written by me: I confirm that my contribution is made under the terms of the Apache 2.0 license.):
```
        if file.name.endswith(".json"):
            if file.name == "terraform.tfvars.json" or file.name.endswith(".auto.tfvars.json"):
                is_vars = True
            elif file.name.endswith(".tfvars.json"):
                # Don't load these (per TF var load rules)
                continue
            with open(file, "r") as f:
                data = json.load(f)
        elif file.name.endswith(".tf") or file.name.endswith(".tfvars"):
            if file.name == "terraform.tfvars" or file.name.endswith(".auto.tfvars"):
                is_vars = True
            elif file.name.endswith(".tfvars"):
                # Don't load these (per TF var load rules)
                continue
            data = _load_hcl_as_json(file)
            if data is None:
                continue
```
