### ISSUE TITLE
CKV_K8S_15 description is misleading

### ISSUE THREAD

**Issue by alsyia** [bridgecrewio/checkov#3458]
Hi,

**Describe the issue**
Check CKV_K8S_11 checks that CPU limits are set. Its current description on https://docs.bridgecrew.io/docs/bc_k8s_10 states this:
> Containers cannot use more CPU than the configured limit. Provided the system has CPU time free, a container is guaranteed to be allocated as much CPU as it requests.

As far as I know (I might be wrong), the sentence `Provided the system has CPU time free, a container is guaranteed to be allocated as much CPU as it requests.` is true even without limits!

When it comes to CPU, _requests_ ensures a container can't starve others (through configuration of the CPU cgroup relative weight), not _limits_. Limits CPU time i.e. burst capacity (through configuration of the CPU cgroup quota).

Besides, there are a lot of blog posts out there explaining why CPU limits usually do more harm than good.
 [Very recent example here](https://home.robusta.dev/blog/stop-using-cpu-limits/).
Learning material like [learn.k8s.io](https://learnk8s.io/production-best-practices) often advise to disable CPU limits entirely:
![image](https://user-images.githubusercontent.com/4249034/188150109-090051fe-1a53-4efc-80a0-304f8a2d8a6e.png)

Now, setting CPU limits can sometimes still be used to tell the scheduler was the QoS of the pod is.

Overall, I think that the description is misleading, and I'm not sure why the check is there in the first place. What do you think?

Apologies if this is not the right place to post this issue!

**Examples**

N/A

**Version (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by gruebel** [comment]
Hey @alsyia thanks for reaching out. I know that article and it is bit sad, that the author references the official Kubernetes docs from 2018. The current text reads differently and doesn't indicate that anymore

> The CPU limit defines a hard ceiling on how much CPU time that the container can use. During each scheduling interval (time slice), the Linux kernel checks to see if this limit is exceeded; if so, the kernel waits before allowing that cgroup to resume execution.
The CPU request typically defines a weighting. If several different containers (cgroups) want to run on a contended system, workloads with larger CPU requests are allocated more CPU time than workloads with small requests.

https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#:~:text=The%20CPU%20limit,with%20small%20requests.

Also here from the official GCP blog

> Kubernetes looks for Pods that are using more resources than they requested. If your Pod’s containers have no requests, then by default they are using more than they requested, so these are prime candidates for termination. Other prime candidates are containers that have gone over their request but are still under their limit.

https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-resource-requests-and-limits#:~:text=Kubernetes%20looks%20for,under%20their%20limit.

So, at the end, it depends. If you think setting CPU requests is enough, then skip the limit check 🙂

**Comment by alsyia** [comment]
Thanks for your answer! 

I agree the doc changed, but as far as I know how it works under the hood did not, limits cause throttling and don't solve contention. Requests are enough to ensure pods get what they reserved.

Regarding termination, Google's blog post is clear that lack of CPU limits will not cause termination:
> This means the CPU will be artificially restricted, giving your app potentially worse performance! However, it won’t be terminated or evicted.

Anyway, we will just skip it since we don't want throttling on our infrastructure, I just wanted to raise that _disabling_ CPU limits is often considered a good practice. 

Thanks again for the quick answer! :smile:

**Comment by aantn** [comment]
Hi, I'm the author of the aforementioned blog post, so if it's alright, I'll chime in:
 
Some people like limits, some people (e.g. yours truly) would rather protect workloads by setting requests and not limits. Both are viable strategies, with implications on p99 latency and utilization.

Regardless of what you prefer, I agree with @alysia that following sentence is misleading: `Provided the system has CPU time free, a container is guaranteed to be allocated as much CPU as it requests.`

Everything in the sentence is true, but it has nothing to do with the CPU limit check

I would go a little further and argue that the following sentence is factually inaccurate:

  A system without managed quotas could eventually collapse due to inadequate resources for the tasks it bares.

A more accurate statement would be:

  Without quotas or accurate requests, workloads can be starved for resources they need.

But I suppose it doesn't really matter anyway. People who want to pay attention to this check will do so, those who want to ignore it will do so regardless of the text.
