### ISSUE TITLE
Checkov should not exit success (0) on parsing errors

### ISSUE THREAD

**Issue by m-wynn** [bridgecrewio/checkov#35]
**Describe the bug**
Checkov exits 0 on success and 1 [on any failed checks](https://github.com/bridgecrewio/checkov/blob/a9c8e2c426dafe72182935ca230f74136c42e9f9/checkov/terraform/output/report.py#L59).

It also returns 0 on parsing errors.  It should probably return something else, to cause CI pipelines to fail instead of quietly succeeding.

**To Reproduce**
1. `echo "hello" > ./bad.tf`
2. `checkov -d .`
3. See that there is a parsing error, but checkov exits 0.

```
$ checkov -d .
       _               _              
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V / 
  \___|_| |_|\___|\___|_|\_\___/ \_/  
                                      
version: 1.0.98 

Passed checks: 0, Failed checks: 0, Skipped checks: 0, Parsing errors: 1

$ echo $?
0
```

**Expected behavior**
Checkov should return something non-zero (maybe 2?)

```
$ checkov -d .
       _               _              
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V / 
  \___|_| |_|\___|\___|_|\_\___/ \_/  
                                      
version: 1.0.98 

Passed checks: 0, Failed checks: 0, Skipped checks: 0, Parsing errors: 1

$ echo $?
2
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Checkov Version: 1.0.98

**Comment by angatha** [comment]
Hi @m-wynn is there a reason why this wasn't merged?

I checked the changes by myself and for me they make sense.
Now we have not just a single return code but have to merge multiple exit code from all the runners.
My suggestion would be:

- return 2 if any parsing error occurs
- otherwise of a check failed 1
- otherwise 0

Then there is the new soft fail feature.
For a run without specifying the output, I don't get an indication that a parsing error occurred.
Maybe this is a whole other point, but if we return 0 even if there are parsing errors, the user may interpret this wrong.
One solution would be to have a separate flag that disables return code 2.
