### ISSUE TITLE
AWS Route 53 checks (CKV2_AWS_38 and CKV_AWS_39) false positive in Terraform Plan framework

### ISSUE THREAD

**Issue by citrix-eg** [bridgecrewio/checkov#3562]
**Describe the issue**
AWS Route 53 DNSSEC and Query Logging checks flag as false positive in Terraform Plan framework.

**Examples**
Use Hashicorp's basic example to reproduce

**Version (please complete the following information):**
 - 2.1.226

**Additional context**
Create a new file/project using the Hashicorp example given
Run a vanilla check: `checkov -f foo.tf --quiet --compact -c CKV2_AWS_39`. Observe no issues.
Create a plan and format it with json: `terraform plan -out tfplan.bin && terraform state show tfplan.bin > tfplan.json`
Check it with terraform_plan framework: `checkov -f tfplan.json --framework terraform_plan --compact --quiet -c CKV2_AWS_39`. Observe it fail.

This same behavior occurs with CKV2_AWS_38 as well using the same basic example, and again--only with Terraform Plan: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_hosted_zone_dnssec

**Comment by gruebel** [comment]
hey @citrix-eg thanks for reaching out. I can't reproduce it for `CKV2_AWS_38`, but for `CKV2_AWS_39` I found the reason, probably it will be the same for the other one. The problem is that the resource `aws_route53_query_log` has no values initially in the TF plan and therefore we exclude it, because we think it is not a real resource.
