### ISSUE TITLE
Checkov returns 0 exit code after encountering an error processing Helm chart

### ISSUE THREAD

**Issue by cameronwaterman** [bridgecrewio/checkov#3619]
**Describe the issue**

_Current state_

When Checkov encounters an error processing a Helm chart, it still returns a 0 exit code. I'm assuming it is calling `helm template` under the hood, which does return a non-zero exit code in this case.

```
[INFO ]  Error parsing output dataframeservice at dir: ./. Working dir: C:\Users\cwaterma\AppData\Local\Temp\tmp1tgnonhc.
Traceback (most recent call last):
  File "C:\Users\cwaterma\AppData\Local\Programs\Python\Python37\lib\site-packages\checkov\helm\runner.py", line 243, in _convert_chart_to_k8s
    Runner._parse_output(target_dir, o)
  File "C:\Users\cwaterma\AppData\Local\Programs\Python\Python37\lib\site-packages\checkov\helm\runner.py", line 116, in _parse_output
    output_str = str(output, 'utf-8')
TypeError: decoding to str: need a bytes-like object, NoneType found

...
...

[DEBUG]  No failed checks, or soft_fail is True and soft_fail_on and hard_fail_on are empty - returning 0
```

_Expected state_

Checkov returns a non-zero exit code when it encounters an error processing a Helm chart. I'm running this in an Azure pipeline and would expect the scan task to fail if it cannot run the scan.

**Comment by cameronwaterman** [comment]
@gruebel - Could you provide some insight into how issues for this repo are typically triaged and addressed? Just wanting to get an idea on a timeline for a fix or feedback on the issue.

**Comment by gruebel** [comment]
hey @cameronwaterman, sure I can try to give a rough prioritization order.
Prio

1.  Any kind of crash/hang. If it is easily reproducible, then it will be tackled in a fast manner.
2. Bugs in the most used frameworks, like Terraform, CFN, ARM/Bicep and K8s
3. Bugs in other frameworks
4. Feature requests

For this specific issue it will be a prio of 3-4. Because it doesn't block anyone from scanning and it is not a bug from actually converting the helm chart to Kubernetes manifests, otherwise you would have created a different ticket for it. And now comes actually the tricky part, strictly speaking, adjusting the current behaviour from returning exit code 1 instead of 0 is a breaking change. As far as I can tell, if we encounter any error during parsing/processing helm charts, we return an exit code of 0. So, it is not only this specific error, but a couple more, which would need to be addressed. Lastly, you are actually the first one to raise this kind of issue, so compared to other existing issues it will take time till someone of us will tackle it.

I need to clarify, if we will treat it as a breaking change, because this behaviour exists, since the framework was added to `checkov` and is nothing, which was added accidentally in the last weeks.

**Comment by cameronwaterman** [comment]
Thanks for your quick response @gruebel. I'm not sure I understood your last sentence, though.

> I need to clarify, if we will treat it as a breaking change, because this behaviour exists, since the framework was added to checkov and is nothing, which was added accidentally in the last weeks.

Could you help me understand what this means?

**Comment by davidcorrigan714** [comment]
This really should be fixed. Just noticed our CI/CD process was ignoring charts because they couldn't render. It's bizarre that checkov is returning a normal error code when it bailed before actually do any scanning.

**Comment by amilcarlucas** [comment]
Please re-open this

**Comment by pczern** [comment]
if we have a key like `imagePullSecrets[0].name` in the helm chart but no value for the name specified the yaml isn't scanned because of this error, but we get zero exit code returned by checkov
If our chart is missing things and can't be scanned we need to know and throw an error, otherwise we don't notice if our charts are not scanned because they are broken
helm lint works without issues

**Comment by pczern** [comment]
https://github.com/bridgecrewio/checkov/blob/83f99b0af27f0d3c85d1eb913ef6edcdd15433a0/checkov/kubernetes/parser/parser.py#L33
This is the line where the just mentioned error is catched and the debug message is printed, but there is only a message in debug mode and it does not use non zero exit code though it is an error

**Comment by pczern** [comment]
This is another place that does not trigger a non-zero exit code but should
https://github.com/bridgecrewio/checkov/blob/83f99b0af27f0d3c85d1eb913ef6edcdd15433a0/checkov/helm/runner.py#L308
