### ISSUE TITLE
Code lines for this resource are too many

### ISSUE THREAD

**Issue by rosshukla1** [bridgecrewio/checkov#3753]
Received this issue: "Code lines for this resource are too many. Please use IDE of your choice to review the file."
for Terraform code. AKS clusters frequently have many lines of code, I added no additional configuration than what is offered by Terraform.

Version: Checkov Version 2.2.0

Desired Outcome: 
1. Limit is increased for resources like AKS that frequently have many lines of code. 
2. Can you please explain this error, such as the actual limit to the number of code lines? 
3. Even with this error, Checkov produces checks that are not accurate, perhaps due to unpredictable behavior. Can this be fixed?

Example:

    Check: CKV_AZURE_5: "Ensure RBAC is enabled on AKS clusters"
	    FAILED for resource: azurerm_kubernetes_cluster.aks_cluster
	    File: ***/aks_cluster/main.tf:42-135
    
		    Code lines for this resource are too many. Please use IDE of your choice to review the file.

Note: I do have RBAC enabled.

**Comment by gruebel** [comment]
hey @rosshukla1 thanks for reaching out. We are cutting the output if it is bigger than 50 lines for a resource. This was added, because some resources are just too big and therefore there is no value in adding the actual code into the output. You can adjust this behaviour by setting following env var to the number you like
```shell
export CHECKOV_OUTPUT_CODE_LINE_LIMIT=100
```
depending on the actual code there is always a chance we can't correctly evaluate what you tried to achieve and therefore show a false positive.

**Comment by rosshukla1** [comment]
@gruebel ok so the error "Code lines for this resource are too many" just refers to the display/output, and is not associated with the accuracy of the scanning? just want to confirm, thanks!

**Comment by gruebel** [comment]
yes, correct.
Sure, if it is possible to create a simple example to show a false positive, then just create a new issue with the resource config, the result you get and what you actually would have expected. Similar to this issue #3749, but no need to dive into the code deeply 🙂

**Comment by rosshukla1** [comment]
awesome, thanks @gruebel
