### ISSUE TITLE
checkov skips all K8S standard policies if one or more custom policy is specified in --checks

### ISSUE THREAD

**Issue by previ** [bridgecrewio/checkov#4196]
**Description**
Using checkov to verify a kubernetes manifests (a single file with several objects: deployments, configmaps, etc) against a list of checks (so using the --check parameter), checkov verifies only the first check, and appears to skip all others checks in the provided list.

**Examples**
The [manifests are available here](https://gist.github.com/previ/cf193061c767f18be7616dd52739adb0#file-k8s-manifest-yaml)
The [parameters available in the log](https://gist.github.com/previ/cf193061c767f18be7616dd52739adb0#file-full_log_debug-log-L33)

**Version (please complete the following information):**
 - Checkov Version 2.2.232

**Additional context**
The [full log, LOG_DEVEL=DEBUG, is available here](https://gist.github.com/previ/cf193061c767f18be7616dd52739adb0#file-full_log_debug-log)
The custom policies yaml files are available [here](https://gist.github.com/previ/cf193061c767f18be7616dd52739adb0#file-k8s_pvc_gov01-yaml) and [here](https://gist.github.com/previ/cf193061c767f18be7616dd52739adb0#file-k8s_sts_gov01-yaml)

**Comment by gruebel** [comment]
hey @previ thanks for reaching out.
you found quite an interesting problem, we have a special logic for Kubernetes checks, because you can also use `--check` and `--skip-check` with a Kubernetes namespace, ex `checkov -d . --skip-check kube-system`
Luckily `_` are not allowed for namespace names, therefore I will adjust the logic to allow custom checks as long as they an `_` in their ID.
