### ISSUE TITLE
CKV_AZURE_59 should pass on allow_blob_public_access and allow_nested_items_to_be_public depending on weather AzureRM v >= 3.0

### ISSUE THREAD

**Issue by mrgyllen** [bridgecrewio/checkov#4389]
**Describe the issue**
I am working on a terraform script to create an Azure Storage Account and I want to use good->best practices and comply to known security checks by using Checkov. One of the checks that I don't pass is the CKV_AZURE_59 - "Ensure Azure storage account does not allow blob containers with public access" and it fails even though I have read the upgrade instructions on [terraform.io](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide) and am using the correct settings (I think :-)). I am using AzureRM >3.0 which means that I can't use `allow_blob_public_access` to secure public access because it has been renamed to `allow_nested_items_to_be_public` in AzureRM v 3.0. 

I have tried to use allow_blob_public_access but obviously terraform validate fails but checkov also returns the CKV_AZURE_59.

**Examples**
```
resource "azurerm_storage_account" "tfstate" {
  name                     = module.storage_account_label.id 
  resource_group_name      = azurerm_resource_group.tfstate.name
  location                 = azurerm_resource_group.tfstate.location
  account_tier             = var.storage_account_tier
  account_replication_type = var.storage_account_replication_type
  access_tier              = "Hot"
  account_kind             = "StorageV2"

  identity {
    type = "SystemAssigned"
  }

  # Security
  # public_network_access_enabled   = false
  enable_https_traffic_only       = true
  min_tls_version                 = "TLS1_2"
  # Check: CKV_AZURE_59: "Ensure that Storage accounts disallow public access"
  allow_nested_items_to_be_public = false
  # Azure Resource Manager: 3.0 Upgrade Guide - The field 'allow_blob_public_access' will be renamed to 'allow_nested_items_to_be_public'
  #allow_blob_public_access        = false

  # Check: CKV_AZURE_33 "Ensure Storage logging is enabled for Queue service for read, write and delete requests"
  queue_properties {
    logging {
      delete                = true
      read                  = true
      version               = "2.0"
      write                 = true
      retention_policy_days = "10"
    }
  }

  tags = {
    environment = var.environment
  }
}
```

Output (checkov -d .)
```
FAILED for resource: azurerm_storage_account.tfstate
	File: /main.tf:19-57
	Guide: https://docs.bridgecrew.io/docs/ensure-that-storage-accounts-disallow-public-access

		19 | resource "azurerm_storage_account" "tfstate" {
...
...

```

**Version (please complete the following information):**
 - Checkov Version: **2.2.326**

**Additional context**

**Comment by SteveBurkettNZ** [comment]
Yes, agreed, getting the same thing. This needs fixing.  But it's kind of funky.

CKV_AZURE_59 has a name of **Ensure that Storage accounts disallow public access**, pointing to a [Guideline doc](https://docs.bridgecrew.io/docs/ensure-that-storage-accounts-disallow-public-access) which is titled **Ensure Azure storage account does not allow blob containers with public access** and is about changing the access level on the blob container.

The StorageAccountDisablePublicAccess [check](https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/azure/StorageAccountDisablePublicAccess.py) looks to still be looking for **allow_blob_public_access** that was used AzureRM <3.0

However, the same named [test](https://github.com/bridgecrewio/checkov/blob/main/tests/terraform/checks/resource/azure/test_StorageAccountDisablePublicAccess.py) is using [example_StorageAccountDisablePublicAccess](https://github.com/bridgecrewio/checkov/blob/main/tests/terraform/checks/resource/azure/example_StorageAccountDisablePublicAccess/main.tf) which is looking for **public_network_access_enabled = false** in order to pass it. 

Seems to be some sort of mix-up between deny public access at the storage account level vs deny public access at the container blob level?

@JamesWoolfenden : Any ideas?

**Comment by JamesWoolfenden** [comment]
docs are written after, if in doubt - trust in the code which has my dabs all over it.
the check is looking at     
```
def get_inspected_key(self) -> str:
        return "public_network_access_enabled"
```
Which is a current setting for storage accounts.
so go for 
public_network_access_enabled = false
to pass.

Docs needs changing.

**Comment by JamesWoolfenden** [comment]
I changed the docs.

**Comment by SteveBurkettNZ** [comment]
Thanks for the reply @JamesWoolfenden! 

Just out of interest, in which file are you seeing that check is looking for "public_network_access_enabled"?

I was looking at the [StorageAccountDisablePublicAccess.py](https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/azure/StorageAccountDisablePublicAccess.py) file in master, which has **id = "CKV_AZURE_59"** and :

`
def get_inspected_key(self):
        return "allow_blob_public_access"
`

FWIW, I don't seem to get a pass with **public_network_access_enabled = false**.   : (

**Comment by JamesWoolfenden** [comment]
You had me worried. You're looking in the wrong branch, we don't use master anymore we use main.

**Comment by SteveBurkettNZ** [comment]
Doh!  Thanks for the confirmation.
