### ISSUE TITLE
Terragrunt Suppressing specific resource blocks

### ISSUE THREAD

**Issue by ChaseFreeman17** [bridgecrewio/checkov#4690]
**Describe the issue**
I am currently attempting to use the suggested method for Terragrunt, #1284. When using this method the comments are not pulled into the final JSON document that is scanned by Checkov, therefor not allowing the use of suppressing resource block. This method otherwise works best as it downloads all of the modules and is a complete representation of what will be built. Suppressing the entire rule is not an option as we will want this to be ran the same way across thousands of terraform folders.

```
terragrunt init
terragrunt plan -out tf.plan
terragrunt show -json tf.plan  > tf.json 
checkov -f tf.json
```

**Examples**
Please share an example code sample (in the IaC of your choice) + the expected outcomes.

```
resource "aws_iam_role_policy_attachment" "task_admin" {
  #checkov:skip=CKV_AWS_274:Comment to surpress
  role       = module.ecs_service_task.task_role_name
  policy_arn = "arn:aws:iam::aws:policy/AdministratorAccess"
}
```

**Version (please complete the following information):**
 - Checkov Version 2.3.96

**Additional context**

Does anyone have any suggestions?

**Comment by gruebel** [comment]
hey @ChaseFreeman17 thanks for reaching out.

Since we don't support `terragrunt` we also can't do anything with the comments written in those files. We do support those use cases for native Terraform with the flag `--repo-root-for-plan-enrichment`.

Since we don't plan to support `terragrunt` any time soon, I'm closing the feature request for the time being.
