### ISSUE TITLE
Scanning IAM Role Public Access

### ISSUE THREAD

**Issue by kmroz0991** [bridgecrewio/checkov#473]
Describe the bug
It seems when specifying more than one  json, the policy does not scan all principals, rather it looks at the first one. 

To Reproduce

Create policy with more than one SID
`resource "aws_iam_role" "lambdaRole" {
  name               = "test-role"
  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
      {
        "Action": "sts:AssumeRole",
        "Principal" : {"Service": "lambda.amazonaws.com"},
        "Effect": "Allow"
      },
      {
        "Action": "sts:AssumeRole",
        "Principal" : {"AWS": "*"},
        "Effect": "Allow"
      },
      {
        "Action": "sts:AssumeRole",
        "Principal" : {"Service": "events.amazonaws.com"},
        "Effect": "Allow"
      },
  ]
}

EOF
}`
Run Checkov against policy
Expected behavior
I would expect the scan to check each json within the policy rather than the first one

Desktop (please complete the following information):

OS: Mac
Checkov Version: 1.0.459

**Comment by nimrodkor** [comment]
Hey @kmroz0991 !

Thanks for reporting. We've identified the issue and solved it, and will release a fix soon. However, please note your JSON policy is not a valid JSON since it has a trailing comma after the last statement. That isn't supported by JSON officially, and so after the fix and removing the comma, you should see the expected behavior.
