### ISSUE TITLE
CKV_AWS_40 claim to reduce access management complexity but might lead to an increase in complexity

### ISSUE THREAD

**Issue by Porkepix** [bridgecrewio/checkov#482]
**Describe the bug**
CKV_AWS_40 claim to reduce access management complexity but might lead to an increase in complexity.

I'll explain myself here:
One of the ways Terraform can be used is by having a directory for one project. Oftentimes, you might want that project to be the most self-sufficient possible.

We got a case where, for a given directory, it complained in several places.
1/ A `aws_iam_user_policy_attachment` used twice, for two human users.
2/ A `aws_iam_user_policy` used once, for a system user (A user created with the single purpose of providing SES accesses, and therefore credentials to use).

While I can understand what the rule is trying to achieve in the first case, because indeed, this could be factorized with a single group, this would I think only make sense if those users are related in some way, so that the created group have some semantics, and isn't only here for the purpose of doing a single policy attachment. The later case is imho a bit more problematic, but couldn't be spotted by some automatic ways.

What's more problematic I think is both case 2/ and case 1/ after I removed one of the users. This means that while there's a policy attachment that's done to a single user, that rule asks us to create a group that will contain a single user, only to be satisfied, but at the cost of increasing complexity: creating a group for a single user, if it's known this group will never contain any user ever or in a foreseeable future isn't what I would expect about a good practice.

So at think this rule at the very least shouldn't be triggered for single-attachment cases, or at the very least it should be allowed to flag rules to be ignored directly from within targeted directories.

**Comment by Porkepix** [comment]
I believe issue is still around. I guess issue isn't that high, but we had to put tag to ignore it.
Slack unfortunately isn't a very FLOSS-friendly tool, but it would be pleasure to talk about it on IRC, Matrix or XMPP :)

**Comment by nimrodkor** [comment]
Hey @Porkepix !

Sorry for the late reply!

It is considered bad practice to assign policies (inline or otherwise) to users, as user permissions need to be handled by using groups. I think the general case, where human users gain permissions via the role they fill in the organization fits this scheme - so for example, when looking at use case number 1 - I'd expect there to be a group with that policy attached, and the users become members of that group.
Use case number 2 is really a different use case, where the IAM user is just an external service requiring access to AWS. In that case, a suppression with the justification that it's a service user should resolve this issue. Something along the lines of:
```terraform
resource "aws_iam_user_policy" "service_user_policy" {
  # checkov:skip=CKV_AWS_40:Used by a service user
  ...
  ...
}
```

Does that sound good?

**Comment by gruebel** [comment]
To give some extra background to the check, it belongs to the CIS Benchmark recommendations and therefore we won't remove it any time soon. As with any recommendation there can be always valid cases not to do it and then a skip comment with some proper reason informs everyone, why this deviates.
