### ISSUE TITLE
Allow var-file to be passed as environment variable

### ISSUE THREAD

**Issue by roddick-mark** [bridgecrewio/checkov#5240]
**Describe the issue**
Currently you can only pass a Terraform var-file via a command line argument (--var-file). It would be useful to be able to source this from an environment variable.

**Version (please complete the following information):**
 - Checkov Version [2.3.285]

**Comment by gruebel** [comment]
hey @roddick-mark thanks for reaching out.

If you are interested you can easily contribute the needed change. Just add here

https://github.com/bridgecrewio/checkov/blob/e2aa231efeed33e1a9dff389f70a5dd652f0f5fc/checkov/common/util/ext_argument_parser.py#L386-L393

following extra line
```python
env_var="CKV_VAR_FILE",
```

not need to write a test for it, because it is a functionality of the library we use and it works for other cases very well so far.

**Comment by kwame-mintah** [comment]
@gruebel, I've picked up this issue.
