### ISSUE TITLE
Plans to support Python (boto3) for IaC misconfigurations

### ISSUE THREAD

**Issue by cbhat-ie** [bridgecrewio/checkov#5326]
Since Python(boto3) to infrastructure is becoming very popular, wondering if Checkov is planning to support scanning Python code for misconfigurations that could potentially result in vulnerabilities in the deployed infrastructure. This is a gap in the IaC-SAST tooling today.

**Comment by gruebel** [comment]
hey @cbhat-ie thanks for reaching out.

Interesting use case, do you have some specific AWS services in mind? Any reason why not use CDK, not extensive enough?

**Comment by cbhat-ie** [comment]
For example, boto3 is used in https://github.com/awslabs/aws-dataall, it is also used to create clusters from MWAA.

**Comment by cbhat-ie** [comment]
Hi @gruebel , did you get a chance to review this?

**Comment by gruebel** [comment]
Hey @cbhat-ie, I can't go into to much detail, but support for `boto3` and the other AWS SDKs will not come anytime soon at least as built-in checks/policies.

**Comment by cbhat-ie** [comment]
That's a pity. Thanks for the update @gruebel. I am still unclear about what the best practice for infrastructure-as-code is: using IaC templates like CFN, TF, etc or SDKs like Python's boto3.

Application SAST is probably better suited to fill this gap.

**Comment by gruebel** [comment]
typically in bigger organizations IaC tools via templates are easier to manage and you have better tooling around it, because there are less rules around it compared to a normal programming language.

Probably something like AWS CDK would fit better for you. You can still write IaC in your favourite language, but have more possibilities on validating what you did, either directly via a SAST tool or on the generated CFN templates via an IaC "SAST" tool.

**Comment by cbhat-ie** [comment]
What do you mean by "directly via a SAST tool"? Are you talking about application SAST tools here?

**Comment by gruebel** [comment]
yes correctly.

**Comment by cbhat-ie** [comment]
Thanks for all the information. Closing this issue.
