### ISSUE TITLE
Secret Scanner for Git history fails

### ISSUE THREAD

**Issue by coffeecoco** [bridgecrewio/checkov#5754]
**Describe the issue**
Apparently when a scan is run in gitlab pipeline and there is a merge request
Apparently the HEAD is dettached, so when checkov git history scan runs checkov fails

**Exception Trace**
git branch
* (HEAD detached at zzzzz)
  master

  File "/User/python3.11/site-packages/checkov/secrets/runner.py", line 181, in run
    git_history_scanner.scan_history(last_commit_scanned=runner_filter.git_history_last_commit_scanned)
  File "/User/python3.11/site-packages/checkov/secrets/scan_git_history.py", line 61, in scan_history
    scanned = self._scan_history(last_commit_scanned)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/User/python3.11/site-packages/checkov/secrets/scan_git_history.py", line 75, in _scan_history
    commits_diff.extend(self._get_commits_diff(last_commit_sha=last_commit_scanned))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/User/python3.11/site-packages/checkov/secrets/scan_git_history.py", line 133, in _get_commits_diff
    commits = list(self.repo.iter_commits(self.repo.active_branch))
                                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/User/python3.11/site-packages/git/repo/base.py", line 896, in active_branch
    return self.head.reference
           ^^^^^^^^^^^^^^^^^^^
  File "/User/python3.11/site-packages/git/refs/symbolic.py", line 309, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to '005dd5ceedd5f7aaaa20b637765965e6e51211aaa'

This is a little bit of a bother because we wanted checkov to run on merge requests as well, if it cant be because thats how git works?
Okay is there a way to avoid this scenario from happening?

**Comment by Saarett** [comment]
Hello @coffeecoco, thank you for reaching out to us with this issue.

As of now, scanning for secrets in history with Checkov is designed exclusively for full repository scans on a periodic basis, rather than for PR/MRs. Running a history scan is primarily useful when scanning the full repository, not on a PR/MR basis. Incorporating this functionality would necessitate additional development.

However, we understand you are interested in this capability and we will add this issue to our backlog for future consideration or we would welcome a contributed a solution.

**Comment by coffeecoco** [comment]
Ok so the fix for now is, exclude this from running on merge requests

**Comment by Saarett** [comment]
@coffeecoco Correct 🙂
