### ISSUE TITLE
CKV_AWS_249 imprecise description

### ISSUE THREAD

**Issue by maksym-severyn** [bridgecrewio/checkov#5850]
**Describe the issue**

I have got a CKV_AWS_249, preparing aws_ecs_task_definition.
In console I have an output 
**"Check: CKV_AWS_249: "Ensure that the Execution Role ARN and the Task Role ARN are different in ECS Task definitions"**
but guide (https://docs.prismacloud.io/en/enterprise-edition/policy-reference/aws-policies/aws-iam-policies/ensure-the-aws-execution-role-arn-and-task-role-arn-are-different-in-ecs-task-definitions) says the opposite: 
"AWS Execution Role ARN and Task Role ARN are different in ECS Task definitions"
and generally it is empty. 
![image](https://github.com/bridgecrewio/checkov/assets/87810252/e3255457-0cd8-40ac-9a38-50599d7d7b12)

Could you provide more information about that check, or give some link to the documentation describing that?

**Version**
 - Checkov Version 3.1.29

**Comment by gruebel** [comment]
Hey @maksym-severyn thanks for reaching out.

This is intentional, the docs relate more to how it looks like in the platform, compared to how it looks like as local scanner.

The reasoning behind the check is to not reduce the needed permissions per role and minimize the blast radius. If someone is able to hack into your ECS task, then it will only have the task role permissions, which are application centric. But if both roles are the same, then the bad actor also gains access to CloudWatch logging or pulling ECR images.
