### ISSUE TITLE
Custom Policy for Terraform Plan Scanning

### ISSUE THREAD

**Issue by danieljpowley** [bridgecrewio/checkov#5858]
I've been tinkering away with Checkov, scanning Terraform Plans in Azure DevOps. I'm under the impression that I can direct scans onto Created and Updated resources in the plan, almost like an incremental scan. However, when I run

Checkov -c $(Agent.ToolsDirectory)/checkov_policy/custom_policy.yml it finds nothing -

File Contents:
{"passed": 0, "failed": 0, "skipped": 0, "parsing_errors": 0, "resource_count": 0, "checkov_version": "3.1.21"}
Finishing: CmdLine

There's 68 newly created resources and at least 30 updated resources - badly configured to flag up some findings.

If I run it as --external-checks-dir I get about 800 new findings and the rest on top for Azure and K8's.

I'm running it as a YAML file -
---
 metadata:
  name: "Check for Change Actions"
  id: "CHANGE_ACTION_POLICY"
  category: "GENERAL_SECURITY"

scope:
  provider: "Terraform"

definition:
  or:
    - cond_type: "attribute"
      resource_types: "all"
      attribute: "__change_actions__"
      operator: "contains"
      value: "create"
    - cond_type: "attribute"
      resource_types: "all"
      attribute: "__change_actions__"
      operator: "contains"
      value: "update"

What am I missing here?

**Comment by gruebel** [comment]
hey @danieljpowley thanks for reaching out.

The `change_actions` is not a regular argument of a resource, that's why we renamed it to not overlap with any actual argument to `__change_actions__ `. You can find an example here https://github.com/bridgecrewio/checkov/blob/main/docs/3.Custom%20Policies/Examples.md#basic-query---terraform-plan-resource-not-deleted be aware it doesn't work with completely deleted resources.
