### ISSUE TITLE
BC_AZR_KUBERNETES_1 support for new Terraform provider syntax

### ISSUE THREAD

**Issue by xortim** [bridgecrewio/checkov#656]
**Describe the bug**

BC_AZR_KUBERNETES_1 detects if OMS is configured for the AKS cluster using an older Terraform AzureRM provider syntax resulting in failed tests using newer provider syntax.

**To Reproduce**

1. Create an Azure AKS cluster and use `addon_profile` instead of `oms` to configure logging
```hcl
resource "azurerm_kubernetes_cluster" "this" {
#...
  addon_profile {
    oms_agent {
      enabled                    = var.oms_agent.enabled
      log_analytics_workspace_id = var.oms_agent.log_analytics_workspace_id
    }
#...
}
```

**Expected behavior**

Test should include support for legacy and current/stable version of terraform resource syntax.

**Desktop (please complete the following information):**
 - Checkov Version 1.0.615

**Other comments**

This is failing locally for me. It could be that the provided [guide needs](https://docs.bridgecrew.io/docs/bc_azr_kubernetes_1#) updated and that the check itself is looking for the right addon_profile block. The code block above is failing the check with a default value being null for that object.

**Comment by njgibbon** [comment]
Hello,

Thanks for the report.

In this case it does appear that this check is actually implemented correctly.

On checkov `1.0.615` variable evaulation was not working as you may expect. This was released a few weeks ago with checkov `1.0.634` I think. So, you will have received a false negative due to the variable evaluation, not the check.

If you set `oms_agent.enabled` to `true` explicitly then you should find that the check passes even on `1.0.615`.
```
    oms_agent {
      enabled                               = true
      log_analytics_workspace_id = var.oms_agent.log_analytics_workspace_id
    }
```
I have just re-tested with your exact configuration (and the below var set) on `1.0.665` and now the evaluation works it is all working as expected.
```
variable "oms_agent.enabled" {
 type = boolean
 default = true
}
```
So, if you update checkov all should be good on your end.

However, this should remain open because the Bridgecrew remediation documentation for this check does need updating. https://docs.bridgecrew.io/docs/bc_azr_kubernetes_1#

`1.35.0` is the earliest Azure Provider Documentation that is available from almost 2 years ago and even that does not include the `oms` configuration field. So, it's safe to say that this has been deprecated if it wasn't a mistake.

https://registry.terraform.io/providers/hashicorp/azurerm/1.35.0/docs/resources/kubernetes_cluster

**Comment by VimukthiPerera** [comment]
@njgibbon This does not work with the following configuration for Checkov version 1.0.690

 ```
		61 |   addon_profile {
		62 |     oms_agent {
		63 |       enabled                    = var.oms_agent_enabled
		64 |       log_analytics_workspace_id = var.log_analytics_workspace_id
		65 |     }
		66 | 
		67 |     kube_dashboard {
		68 |       enabled = var.kube_dashboard_enabled
		69 |     }
		70 | 
		71 |     azure_policy {
		72 |       enabled = var.azure_policy_enabled
		73 |     }
		74 |   }
```

**Comment by njgibbon** [comment]
@VimukthiPerera  - Heya. 

That is expected right? 

If `addon_profile.oms_agent.enabled == false` then the check will fail as expected because logging is not enabled.

**Comment by VimukthiPerera** [comment]
Oh! Sorry. My mistake. This is working as expected.

**Comment by njgibbon** [comment]
@VimukthiPerera  Ok great! Thanks for feeding back, Just raise an issue if anything else comes up.

The bridgecrew documentation has been changed to reflect the correct usage. Merged by Jo Gore.

This issue can now be closed (: @schosterbarak

**Comment by schosterbarak** [comment]
Thanks @njgibbon
