### ISSUE TITLE
Custom module checks (BaseModuleCheck) are not executed on tfplan 

### ISSUE THREAD

**Issue by brk3** [bridgecrewio/checkov#6679]
**Describe the issue**
When running checkov with Terraform, I find the best results by using `-f tfplan`. I also wish to write a custom policies related to usage of modules in my Terraform. 

The problem is that under no conditions does Checkov seem to execute any custom Python policies that extend `BaseModuleCheck` when running with `-f tfplan`. I have included a small example to demonstrate this issue below.

**Examples**
See [here](https://github.com/brk3/checkov-tfmodule-issue) for an example that reproduces the issue. You can see the output in both the directory and tfplan cases.

**Version (please complete the following information):**
3.2.219

**Comment by gruebel** [comment]
hey @brk3 the reason the check is skipped is quite simple, `checkov` doesn't expose the module definition from a TF plan file. Creating an example is great, but you should have converted the plan file to a JSON file, then it is easier to debug. That being said, `checkov` can only process the JSON representation of a plan file, not the binary plan file.

**Comment by gruebel** [comment]
Strictly speaking the docs only mention resources and a module block is not a resource, same as data, variable or local blocks.

> I can scan the tfplan, or the directory, with a variety of enrichment options. (It's not clear to me when I would want to use one over the other. Perhaps module check is such a case, but this is not specified.)

Both wouldn't help here. One is for propagating the skip comments from TF files to a TF plan scan. And the other is for bridging possible short comings of TF plan files, because they don't expose all data like locals.

> As a policy tool, I expect checkov to hard error in the case it has any issues loading or executing policies. Otherwise it's hard to trust that it will not just silently let violations slip through that it otherwise shouldn't.

How do you except a tool to show you an error, if it doesn't know about the data you want it to check? Similar things will happen, when you accidentally misspell the resource name you want to check, then the check wouldn't run and not show an error, because it doesn't exist.

Also #6204 is not related to your problem, because TF and TF plan resources can look different, this is especially true when a resource is created vs updated.
And #5238 is probably not related to your issue, because there seems to be a general problem with loading the checks, which can have various different reasons.

All in all it is possible to support it and contribution are always welcome.
