### ISSUE TITLE
CKV_AWS_107: aws_iam_policy for action ecr:GetAuthorizationToken with resource "*"

### ISSUE THREAD

**Issue by SoerenVoskuhl0042** [bridgecrewio/checkov#988]
**Is your feature request related to a problem? Please describe.**
We have an aws iam policy with the following statement:
`  statement {
    actions = [
      "ecr:GetAuthorizationToken"
    ]
    resources = [
      "*"
    ]
  }`

checkov fails here with the message CKV_AWS_107: "Ensure IAM policies does not allow credentials exposure" but according to the aws documentation we found [(https://docs.aws.amazon.com/AmazonECR/latest/public/security_iam_id-based-policy-examples.html)](https://docs.aws.amazon.com/AmazonECR/latest/public/security_iam_id-based-policy-examples.html) we need to set resources = "*".

**Describe the solution you'd like**
Is it possible to change the check CKV_AWS_107 to allow the above action with resources = "*"?

**Comment by acdha** [comment]
I think this is an incorrect application of the general guidance: unlike, say, access keys or STS tokens this is how ECRs are intended to be used — the Docker login step is required functionality.

**Comment by schosterbarak** [comment]
adding @kmcquade  wdyt?

**Comment by kmcquade** [comment]
@schosterbarak I can see how this request to change it makes sense. ecr:GetAuthorizationToken doesn't allow for ARN restriction, so that doesn’t mean that the developer is writing the IAM policy wrong. From an attacker perspective, it is useful to know who can get the ECR authorization token, but from the perspective of the person writing the IAM policy, they shouldn’t get dinged for it.

@schosterbarak I believe you leverage the Cloudsplaining library to determine credentials exposure. Is there a way to exclude this action only in the credentials exposure finding for Checkov, while keeping the ecr:GetAuthorizationToken the same in Cloudsplaining?

**Comment by schosterbarak** [comment]
@kmcquade so we would probably want to exclude that if the resource is attached to ECR but to alarm for the rest. 
We don't have that capability yet, but should be available from soon where we will enable resource graph queries in checkov. I'll keep this ticket open for now and will update once the implementation is done

**Comment by kmcquade** [comment]
@schosterbarak I think we are good to close this issue since it was addressed in #1032.

**Comment by schosterbarak** [comment]
Thanks @kmcquade !
